spring:
  ai:
    mcp:
      client:
        enabled: true
        name: embabel
        version: 1.0.0
        request-timeout: 30s
        type: SYNC

        stdio:
          connections:
            brave-search-mcp:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "@brave/brave-search-mcp-server"
                - --disabled-tools
                - brave_summarizer
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
            fetch-mcp:
              command: cmd
              args:
                - /c
                - uvx
                - mcp-server-fetch
                - --ignore-robots-txt
              env:
                PYTHONIOENCODING: utf-8
            puppeteer-mcp:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "@modelcontextprotocol/server-puppeteer"
            wikipedia-mcp:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "wikipedia-mcp"
            github-mcp:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "@modelcontextprotocol/server-github"
              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
            google-maps-mcp:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "@modelcontextprotocol/server-google-maps"
              env:
                GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}